# Generated by Django 5.1.4 on 2025-01-13 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0018_alter_lid_date_of_birth'),
        ('student', '0018_alter_student_date_of_birth'),
        ('tasks', '0002_alter_task_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='performer',
        ),
        migrations.AddField(
            model_name='task',
            name='lid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_lid.lid'),
        ),
        migrations.AddField(
            model_name='task',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_performer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('COMPLATED', 'COMPLATED'), ('WAITING', 'WAITING'), ('ONGOING', 'ONGOING'), ('CANCELLED', 'CANCELLED')], default='WAITING', max_length=50),
        ),
    ]
