# Generated by Django 5.1.5 on 2025-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_lid_alter_task_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='new_student_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='student_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
