# Generated by Django 5.1.5 on 2025-03-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_new_student_date_task_student_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='new_student_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='student_date',
        ),
    ]
