# Generated by Django 5.1.5 on 2025-05-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='is_archiver',
            field=models.BooleanField(default=False),
        ),
    ]
