# Generated by Django 5.1.5 on 2025-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='homework_type',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20, null=True),
        ),
    ]
