# Generated by Django 5.1.5 on 2025-06-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroup', '0002_studentgroup_homework_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='homework_type',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=20, null=True),
        ),
    ]
