# Generated by Django 5.1.5 on 2025-05-30 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroup', '0002_studentgroup_is_archiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='is_archiver',
        ),
    ]
