# Generated by Django 5.1.4 on 2025-01-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingchannel',
            options={'ordering': ['-created_at']},
        ),
    ]
