# Generated by Django 5.1.5 on 2025-05-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
