# Generated by Django 5.1.5 on 2025-03-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='repeated_theme',
            field=models.ManyToManyField(blank=True, related_name='theme_repeated_theme', to='subject.theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='course_work_files',
            field=models.ManyToManyField(blank=True, related_name='theme_course_work_files', to='upload.file'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='extra_work_files',
            field=models.ManyToManyField(blank=True, related_name='theme_extra_work_files', to='upload.file'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='theme_files', to='upload.file'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='homework_files',
            field=models.ManyToManyField(blank=True, related_name='theme_homework_files', to='upload.file'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='theme_photos', to='upload.file'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='theme_videos', to='upload.file'),
        ),
    ]
