# Generated by Django 5.1.5 on 2025-04-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_theme_repeated_theme_alter_theme_course_work_files_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ('created_at',)},
        ),
    ]
