# Generated by Django 5.1.5 on 2025-06-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_alter_theme_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_language',
            field=models.BooleanField(default=False),
        ),
    ]
