# Generated by Django 5.1.5 on 2025-04-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_level'),
        ('subject', '0003_alter_theme_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels_course', to='course.course'),
        ),
    ]
