# Generated by Django 5.1.4 on 2025-01-13 22:34

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
        ('marketing_channel', '0001_initial'),
        ('stages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=120, null=True)),
                ('message_text', models.CharField(blank=True, max_length=120, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2025, 1, 13, 22, 34, 45, 299896))),
                ('education_lang', models.CharField(choices=[('ENG', 'ENG'), ('RU', 'RU'), ('UZB', 'UZB')], default='UZB', max_length=100)),
                ('student_type', models.CharField(default='student', max_length=100)),
                ('edu_class', models.CharField(help_text='Education level at school if student studies at school', max_length=100)),
                ('subject', models.CharField(help_text='Subject that student won at competition', max_length=100, null=True)),
                ('ball', models.IntegerField(blank=True, default=0, help_text='Earned ball at competition', null=True)),
                ('lid_stage_type', models.CharField(choices=[('NEW_LID', 'NEW_LID'), ('ORDERED_LID', 'ORDERED_LID')], default='NEW_LID', max_length=100)),
                ('is_archived', models.BooleanField(default=False, help_text='Is this student archived or not')),
                ('is_dubl', models.BooleanField(default=False, help_text='Is this student duble or not')),
                ('is_student', models.BooleanField(default=False, help_text='Is this student or not')),
                ('call_operator', models.ForeignKey(blank=True, help_text='CallOperator for this lid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_operator', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(blank=True, help_text='Filial for this student', null=True, on_delete=django.db.models.deletion.CASCADE, to='filial.filial')),
                ('lid_stages', models.ForeignKey(blank=True, help_text='NewStudentStages for this student', null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.newlidstages')),
                ('marketing_channel', models.ForeignKey(blank=True, help_text='Marketing channel for this student', null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing_channel.marketingchannel')),
                ('ordered_stages', models.ForeignKey(blank=True, help_text='NewStudentStages for this student', null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.neworedersstages')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
