# Generated by Django 5.1.5 on 2025-04-26 07:11

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
        ('marketing_channel', '0001_initial'),
        ('upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=120, null=True)),
                ('message_text', models.CharField(blank=True, max_length=120, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2025, 4, 26, 7, 11, 33, 267774, tzinfo=datetime.timezone.utc))),
                ('extra_number', models.CharField(blank=True, max_length=100, null=True)),
                ('education_lang', models.CharField(choices=[('ENG', 'ENG'), ('RU', 'RU'), ('UZB', 'UZB')], default='UZB', max_length=100)),
                ('student_type', models.CharField(default='student', max_length=100)),
                ('edu_class', models.CharField(choices=[('SCHOOL', 'School'), ('UNIVERSITY', 'University'), ('NONE', 'None')], default='NONE', help_text='Education level at school if student studies at school', max_length=100)),
                ('edu_level', models.CharField(blank=True, max_length=100, null=True)),
                ('ball', models.IntegerField(blank=True, default=0, help_text='Earned ball at competition', null=True)),
                ('lid_stage_type', models.CharField(choices=[('NEW_LID', 'NEW_LID'), ('ORDERED_LID', 'ORDERED_LID')], default='NEW_LID', max_length=100)),
                ('lid_stages', models.CharField(blank=True, choices=[('YANGI_LEAD', 'YANGI_LEAD'), ('KUTULMOQDA', 'KUTULMOQDA')], help_text="LID's YANGI_LEAD stage type", max_length=100, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('ordered_stages', models.CharField(blank=True, choices=[('KUTULMOQDA', 'KUTULMOQDA'), ('BIRINCHI_DARS_BELGILANGAN', 'BIRINCHI_DARS_BELGILANGAN'), ('YANGI_BUYURTMA', 'YANGI_BUYURTMA')], help_text="LID's YANGI_LEAD stage type", max_length=100, null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Is this student archived or not')),
                ('is_dubl', models.BooleanField(default=False, help_text='Is this student duble or not')),
                ('is_frozen', models.BooleanField(default=False, help_text='Is this student frozen or not')),
                ('is_student', models.BooleanField(default=False, help_text='Is this student or not')),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('call_operator', models.ForeignKey(blank=True, help_text='CallOperator for this lid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_operator', to=settings.AUTH_USER_MODEL)),
                ('file', models.ManyToManyField(blank=True, related_name='lid_file', to='upload.file')),
                ('filial', models.ForeignKey(blank=True, help_text='Filial for this student', null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('marketing_channel', models.ForeignKey(blank=True, help_text='Marketing channel for this student', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_channel.marketingchannel')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lids_photo', to='upload.file')),
                ('sales_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_manager', to=settings.AUTH_USER_MODEL)),
                ('service_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
