# Generated by Django 5.1.5 on 2025-05-29 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('new_lid', '0001_initial'),
        ('student', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.AddField(
            model_name='lid',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject that student won at competition', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.subject'),
        ),
    ]
