# Generated by Django 5.1.5 on 2025-03-15 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 17, 55, 48, 761342, tzinfo=datetime.timezone.utc)),
        ),
    ]
