# Generated by Django 5.1.5 on 2025-03-15 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0002_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 18, 2, 59, 754280, tzinfo=datetime.timezone.utc)),
        ),
    ]
