# Generated by Django 5.1.5 on 2025-04-26 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 4, 26, 7, 15, 24, 790954, tzinfo=datetime.timezone.utc)),
        ),
    ]
