# Generated by Django 5.1.4 on 2025-01-11 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0003_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lid',
            old_name='student_stages',
            new_name='lid_stages',
        ),
        migrations.AddField(
            model_name='lid',
            name='message_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lid',
            name='sender_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 11, 9, 39, 2, 492358)),
        ),
    ]
