# Generated by Django 5.1.5 on 2025-06-02 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0004_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 2, 7, 4, 30, 689212, tzinfo=datetime.timezone.utc)),
        ),
    ]
