# Generated by Django 5.1.4 on 2025-01-11 09:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('marketing_channel', '0001_initial'),
        ('new_lid', '0004_rename_student_stages_lid_lid_stages_and_more'),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='comment',
            field=models.ForeignKey(blank=True, help_text='Comment', null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 11, 9, 43, 15, 233421)),
        ),
        migrations.AlterField(
            model_name='lid',
            name='lid_stages',
            field=models.ForeignKey(blank=True, help_text='NewStudentStages for this student', null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.newlidstages'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='marketing_channel',
            field=models.ForeignKey(blank=True, help_text='Marketing channel for this student', null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing_channel.marketingchannel'),
        ),
    ]
