# Generated by Django 5.1.5 on 2025-03-17 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0004_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='new_student_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lid',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lid',
            name='student_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 12, 39, 34, 63644, tzinfo=datetime.timezone.utc)),
        ),
    ]
