# Generated by Django 5.1.4 on 2025-01-11 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0005_alter_lid_comment_alter_lid_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lid',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lid',
            name='is_dubl',
            field=models.BooleanField(default=False, help_text='Is this student duble or not'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 11, 11, 41, 57, 49723)),
        ),
        migrations.AlterField(
            model_name='lid',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
