# Generated by Django 5.1.5 on 2025-03-17 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0005_lid_new_student_date_lid_ordered_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lid',
            name='new_student_date',
        ),
        migrations.RemoveField(
            model_name='lid',
            name='student_date',
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 12, 40, 7, 479141, tzinfo=datetime.timezone.utc)),
        ),
    ]
