# Generated by Django 5.1.4 on 2025-01-11 11:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0006_alter_lid_options_lid_is_dubl_and_more'),
        ('stages', '0002_neworedersstages_alter_newlidstages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='lid_etap',
            field=models.CharField(choices=[('NEW_LID', 'NEW_LID'), ('ORDERD_LID', 'ORDERD_LID')], default='NEW_LID', max_length=100),
        ),
        migrations.AddField(
            model_name='lid',
            name='ordered_stages',
            field=models.ForeignKey(blank=True, help_text='NewStudentStages for this student', null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.neworedersstages'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 11, 11, 52, 53, 504193)),
        ),
    ]
