# Generated by Django 5.1.4 on 2025-01-11 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0007_lid_lid_etap_lid_ordered_stages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lid',
            name='lid_etap',
        ),
        migrations.AddField(
            model_name='lid',
            name='lid_stage_type',
            field=models.CharField(choices=[('NEW_LID', 'NEW_LID'), ('ORDERED_LID', 'ORDERED_LID')], default='NEW_LID', max_length=100),
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 11, 13, 25, 45, 91588)),
        ),
    ]
