# Generated by Django 5.1.4 on 2025-01-11 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0008_remove_lid_lid_etap_lid_lid_stage_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 11, 13, 40, 43, 861058)),
        ),
    ]
