# Generated by Django 5.1.5 on 2025-06-19 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0008_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 19, 9, 14, 49, 359476, tzinfo=datetime.timezone.utc)),
        ),
    ]
