# Generated by Django 5.1.5 on 2025-03-19 12:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0009_alter_lid_date_of_birth'),
        ('student', '0010_alter_student_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='call_operator',
            field=models.ForeignKey(blank=True, help_text='CallOperator for this lid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 12, 35, 37, 150426, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lid',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
