# Generated by Django 5.1.5 on 2025-06-21 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0010_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 21, 8, 22, 57, 871904, tzinfo=datetime.timezone.utc)),
        ),
    ]
