# Generated by Django 5.1.5 on 2025-03-23 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0010_lid_student_alter_lid_call_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 23, 6, 51, 46, 960157, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lid',
            name='ordered_stages',
            field=models.CharField(blank=True, choices=[('KUTULMOQDA', 'KUTULMOQDA'), ('BIRINCHI_DARS_BELGILANGAN', 'BIRINCHI_DARS_BELGILANGAN'), ('YANGI_BUYURTMA', 'YANGI_BUYURTMA')], help_text="LID's YANGI_LEAD stage type", max_length=100, null=True),
        ),
    ]
