# Generated by Django 5.1.5 on 2025-03-23 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0012_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 23, 7, 3, 54, 350502, tzinfo=datetime.timezone.utc)),
        ),
    ]
