# Generated by Django 5.1.5 on 2025-05-20 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0014_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 5, 20, 16, 38, 11, 168381, tzinfo=datetime.timezone.utc)),
        ),
    ]
