# Generated by Django 5.1.4 on 2025-01-13 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0018_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Is this student or not'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 13, 10, 56, 3, 61959)),
        ),
    ]
