# Generated by Django 5.1.5 on 2025-05-23 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0020_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 5, 23, 12, 0, 8, 27923, tzinfo=datetime.timezone.utc)),
        ),
    ]
