# Generated by Django 5.1.4 on 2025-01-13 11:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0020_lid_call_operator_alter_lid_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='call_operator',
            field=models.ForeignKey(blank=True, help_text='CallOperator for this lid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 13, 11, 32, 26, 136744)),
        ),
    ]
