# Generated by Django 5.1.5 on 2025-05-27 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0021_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 5, 27, 6, 21, 45, 334710, tzinfo=datetime.timezone.utc)),
        ),
    ]
