# Generated by Django 5.1.4 on 2025-01-13 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0021_alter_lid_call_operator_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 13, 11, 32, 31, 992374)),
        ),
    ]
