# Generated by Django 5.1.5 on 2025-03-25 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0022_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 14, 37, 59, 560271, tzinfo=datetime.timezone.utc)),
        ),
    ]
