# Generated by Django 5.1.4 on 2025-01-13 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0022_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lid',
            name='moderator',
        ),
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 13, 11, 36, 20, 381340)),
        ),
    ]
