# Generated by Django 5.1.5 on 2025-03-27 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0025_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 27, 6, 44, 8, 730593, tzinfo=datetime.timezone.utc)),
        ),
    ]
