# Generated by Django 5.1.5 on 2025-03-28 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0029_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 28, 13, 10, 21, 717866, tzinfo=datetime.timezone.utc)),
        ),
    ]
