# Generated by Django 5.1.5 on 2025-05-29 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0029_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 5, 29, 5, 21, 12, 344522, tzinfo=datetime.timezone.utc)),
        ),
    ]
