# Generated by Django 5.1.5 on 2025-03-29 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0030_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 29, 11, 48, 47, 918113, tzinfo=datetime.timezone.utc)),
        ),
    ]
