# Generated by Django 5.1.5 on 2025-03-29 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0031_alter_lid_date_of_birth'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 29, 11, 53, 38, 109084, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lid',
            name='file',
            field=models.ManyToManyField(blank=True, related_name='lid_file', to='upload.file'),
        ),
    ]
