# Generated by Django 5.1.5 on 2025-04-01 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0032_alter_lid_date_of_birth_alter_lid_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 4, 1, 14, 3, 19, 902375, tzinfo=datetime.timezone.utc)),
        ),
    ]
