# Generated by Django 5.1.5 on 2025-04-02 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0034_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 13, 3, 47, 71735, tzinfo=datetime.timezone.utc)),
        ),
    ]
