# Generated by Django 5.1.5 on 2025-05-30 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0035_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 5, 30, 9, 2, 50, 134349, tzinfo=datetime.timezone.utc)),
        ),
    ]
