# Generated by Django 5.1.5 on 2025-04-07 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0037_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 4, 7, 12, 23, 24, 711780, tzinfo=datetime.timezone.utc)),
        ),
    ]
