# Generated by Django 5.1.5 on 2025-04-08 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0038_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 4, 8, 12, 5, 33, 807546, tzinfo=datetime.timezone.utc)),
        ),
    ]
