# Generated by Django 5.1.5 on 2025-04-10 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0041_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 4, 10, 10, 9, 17, 422147, tzinfo=datetime.timezone.utc)),
        ),
    ]
