# Generated by Django 5.1.5 on 2025-06-04 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0047_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 4, 10, 40, 46, 552511, tzinfo=datetime.timezone.utc)),
        ),
    ]
