# Generated by Django 5.1.5 on 2025-06-05 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0048_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 5, 9, 26, 43, 512524, tzinfo=datetime.timezone.utc)),
        ),
    ]
