# Generated by Django 5.1.5 on 2025-06-05 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0049_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 5, 11, 50, 29, 24900, tzinfo=datetime.timezone.utc)),
        ),
    ]
