# Generated by Django 5.1.5 on 2025-06-10 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0051_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 10, 7, 11, 28, 46458, tzinfo=datetime.timezone.utc)),
        ),
    ]
