# Generated by Django 5.1.5 on 2025-06-10 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0052_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 10, 8, 58, 51, 924397, tzinfo=datetime.timezone.utc)),
        ),
    ]
