# Generated by Django 5.1.5 on 2025-06-11 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0056_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 11, 6, 55, 6, 829801, tzinfo=datetime.timezone.utc)),
        ),
    ]
