# Generated by Django 5.1.5 on 2025-06-11 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0057_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 11, 7, 3, 5, 464246, tzinfo=datetime.timezone.utc)),
        ),
    ]
