# Generated by Django 5.1.5 on 2025-06-14 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0063_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 14, 7, 30, 41, 125354, tzinfo=datetime.timezone.utc)),
        ),
    ]
