# Generated by Django 5.1.5 on 2025-06-14 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0065_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 14, 11, 4, 42, 147273, tzinfo=datetime.timezone.utc)),
        ),
    ]
