# Generated by Django 5.1.5 on 2025-06-16 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_lid', '0069_alter_lid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 16, 9, 22, 46, 834488, tzinfo=datetime.timezone.utc)),
        ),
    ]
