# Generated by Django 5.1.5 on 2025-06-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='choice',
            field=models.CharField(choices=[('TeacherFinance', 'TeacherFinance'), ('Bonus', 'Bonus'), ('New_Student', 'New_Student'), ('Tasks', 'Tasks'), ('Students', 'Students'), ('Comments', 'Comments'), ('Monitoring', 'Monitoring'), ('Results', 'Results')], default=1),
            preserve_default=False,
        ),
    ]
