# Generated by Django 5.1.5 on 2025-06-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='choice',
            field=models.CharField(choices=[('TeacherFinance', 'TeacherFinance'), ('Bonus', 'Bonus'), ('New_Student', 'New_Student'), ('Tasks', 'Tasks'), ('Students', 'Students'), ('Comments', 'Comments'), ('Monitoring', 'Monitoring'), ('Results', 'Results'), ('Examination', 'Examination')]),
        ),
    ]
