# Generated by Django 5.1.4 on 2025-01-17 21:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price_type', models.CharField(choices=[('DAILY', 'Daily payment'), ('MONTHLY', 'Monthly payment')], default='DAILY', max_length=100)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('scheduled_day_type', models.CharField(choices=[('EVERYDAY', 'Every day'), ('ODD', 'Toq kunlar'), ('EVEN', 'Juft kunlar')], default='EVERYDAY', max_length=100)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
