# Generated by Django 5.1.5 on 2025-06-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
