# Generated by Django 5.1.5 on 2025-06-12 08:46

import data.student.groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='finish_date',
            field=models.DateTimeField(default=data.student.groups.models.one_year_from_now),
        ),
    ]
