# Generated by Django 5.1.5 on 2025-06-17 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 21, 13, 54, 41, 47364)),
        ),
    ]
