# Generated by Django 5.1.5 on 2025-06-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_homework_history_updater'),
        ('quiz', '0001_initial'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_materials',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_homework',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='results_excel',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='students_count',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='students_excel',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='type',
        ),
        migrations.AddField(
            model_name='exam',
            name='choice',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Unit', 'Unit'), ('Mid_of_course', 'Mid_of_course'), ('Level', 'Level'), ('Mock', 'Mock'), ('Homework', 'Homework')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks_quiz', to='homeworks.homework'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='materials',
            field=models.ManyToManyField(related_name='quiz_materials', to='upload.file'),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='students_count',
            field=models.IntegerField(default=0),
        ),
    ]
