# Generated by Django 5.1.5 on 2025-06-12 08:46

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
        ('homeworks', '0003_homework_history_updater'),
        ('quiz', '0001_initial'),
        ('student', '0008_alter_student_date_of_birth_and_more'),
        ('subject', '0003_subject_is_language'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_materials',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_homework',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='results_excel',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='students_count',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='students_excel',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='type',
        ),
        migrations.AddField(
            model_name='exam',
            name='choice',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Unit', 'Unit'), ('Mid_of_course', 'Mid_of_course'), ('Level', 'Level'), ('Mock', 'Mock'), ('Homework', 'Homework')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 16, 13, 46, 47, 248908)),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks_quiz', to='homeworks.homework'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='lang_group',
            field=models.CharField(blank=True, choices=[('Foreign', 'Foreign'), ('National', 'National')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='materials',
            field=models.ManyToManyField(related_name='quiz_materials', to='upload.file'),
        ),
        migrations.AddField(
            model_name='exam',
            name='options',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='students_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fill_gaps',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listening',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchpairs',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='count',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_homework', to='homeworks.homework'),
        ),
        migrations.CreateModel(
            name='Cloze_Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloze_answer', to='quiz.answer')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('questions', models.ManyToManyField(related_name='cloze_questions', to='quiz.quizgaps')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clozetest_quiz', to='quiz.quiz')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255, null=True)),
                ('is_participating', models.BooleanField(default=True)),
                ('mark', models.CharField(blank=True, max_length=255, null=True)),
                ('student_comment', models.TextField(blank=True, null=True)),
                ('option', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True)),
                ('has_certificate', models.BooleanField(default=False)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_of_student', to='upload.file')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_exam', to='quiz.exam')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrated_student', to='student.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageObjectiveTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_cloze_answer', to='quiz.answer')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_cloze_quiz', to='upload.file')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_cloze_quiz', to='quiz.quiz')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectiveTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('answers', models.ManyToManyField(to='quiz.answer')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectivetest_question', to='quiz.quizgaps')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectivetest_quiz', to='quiz.quiz')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='True_False',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False'), ('Not Given', 'Not Given')], max_length=15, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='True_False_test_question', to='quiz.quizgaps')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='True_False_test_quiz', to='quiz.quiz')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ManyToManyField(related_name='exam_subject', to='subject.subject'),
        ),
    ]
