# Generated by Django 5.1.5 on 2025-05-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_homework_choice_homework_history'),
        ('quiz', '0001_initial'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listening',
            name='type',
            field=models.CharField(choices=[('MultipleChoice', 'MultipleChoice'), ('TFG', 'True False Not Given'), ('YNG', 'Yes No Not Given'), ('Fill_gaps', 'Fill Gaps')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks_quiz', to='homeworks.homework'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_homework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='materials',
            field=models.ManyToManyField(related_name='quiz_materials', to='upload.file'),
        ),
    ]
