# Generated by Django 5.1.5 on 2025-06-18 12:26

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
        ('groups', '0003_groupsalestudent'),
        ('quiz', '0002_remove_exam_end_date_remove_exam_exam_materials_and_more'),
        ('student', '0012_alter_student_date_of_birth_and_more'),
        ('subject', '0003_subject_is_language'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloze_test',
            old_name='answer',
            new_name='sentence',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='students',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='students_count',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AddField(
            model_name='cloze_test',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_cloze_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='lang_foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='lang_national',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default='Test imtihoni'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_of_student', to='upload.file'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='certificate_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_group', to='groups.group'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='option',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fill_gaps',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_fill_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='imageobjectivetest',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_image_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='listening',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_lesson_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='matchpairs',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_match_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='objectivetest',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_objective_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='pairs',
            name='key',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='true_false',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_boolen_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_vocab_file', to='upload.file'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 17, 26, 32, 285367)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ExamCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=255, null=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_certificate_of_student', to='upload.file')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_exam_certificate', to='quiz.exam')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrated_student_certificate', to='student.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('options', models.CharField(blank=True, default=1, max_length=2, null=True)),
                ('lang_foreign', models.BooleanField(default=False)),
                ('lang_national', models.BooleanField(default=False)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_subject_quiz', to='subject.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='options',
            field=models.ManyToManyField(related_name='exam_subject_options', to='quiz.examsubject'),
        ),
    ]
