# Generated by Django 5.1.5 on 2025-06-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_examregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='is_participating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='student_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
