# Generated by Django 5.1.5 on 2025-06-17 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='lang_foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='lang_national',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 21, 17, 0, 59, 522334)),
        ),
    ]
