# Generated by Django 5.1.5 on 2025-06-24 12:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_answer_cloze_test_sentence_and_more'),
        ('subject', '0003_subject_is_language'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examregistration',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='certificate_expire_date',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='has_certificate',
        ),
        migrations.AddField(
            model_name='examcertificate',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_of_student_subject', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_of_student', to='upload.file'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='certificate_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 28, 17, 59, 55, 789080)),
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='option',
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Waiting', 'Waiting')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='option',
            field=models.ManyToManyField(related_name='registration_option_subjects', to='quiz.examsubject'),
        ),
    ]
