# Generated by Django 5.1.5 on 2025-06-18 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_examsubject_lang_foreign_examsubject_lang_national_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default='Test imtihoni'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 15, 6, 7, 662590)),
        ),
    ]
