# Generated by Django 5.1.5 on 2025-06-11 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_homework_history_updater'),
        ('quiz', '0005_cloze_test_imageobjectivetest_objectivetest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_homework', to='homeworks.homework'),
        ),
    ]
