# Generated by Django 5.1.5 on 2025-06-18 10:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('quiz', '0005_exam_name_alter_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_group', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 15, 59, 35, 951581)),
        ),
    ]
