# Generated by Django 5.1.5 on 2025-06-18 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_examregistration_group_alter_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 16, 31, 1, 12122)),
        ),
    ]
