# Generated by Django 5.1.5 on 2025-06-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='count',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=60),
        ),
    ]
