# Generated by Django 5.1.5 on 2025-06-19 09:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_exam_date'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcertificate',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_of_student_subject', to='subject.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 14, 14, 49, 459234)),
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='option',
        ),
        migrations.AddField(
            model_name='examregistration',
            name='option',
            field=models.ManyToManyField(related_name='registration_option_subjects', to='quiz.examsubject'),
        ),
    ]
