# Generated by Django 5.1.5 on 2025-06-19 12:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_examcertificate_subject_alter_exam_date_and_more'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examregistration',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='certificate_expire_date',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='has_certificate',
        ),
        migrations.AddField(
            model_name='examsubject',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_of_student', to='upload.file'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='certificate_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 17, 32, 4, 14903)),
        ),
    ]
