# Generated by Django 5.1.5 on 2025-06-12 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_cloze_test_comment_fill_gaps_comment_and_more'),
        ('subject', '0003_subject_is_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='lang_group',
            field=models.CharField(blank=True, choices=[('Foreign', 'Foreign'), ('National', 'National')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 16, 11, 6, 4, 190881)),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ManyToManyField(related_name='exam_subject', to='subject.subject'),
        ),
    ]
