# Generated by Django 5.1.5 on 2025-06-12 06:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_exam_is_language_exam_lang_group_alter_exam_date_and_more'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='options',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_of_student', to='upload.file'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='option',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 16, 11, 38, 5, 235314)),
        ),
    ]
