# Generated by Django 5.1.5 on 2025-06-24 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 28, 18, 59, 27, 831872)),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Waiting', 'Waiting')], max_length=255, null=True),
        ),
    ]
