# Generated by Django 5.1.5 on 2025-06-12 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_exam_options_examregistration_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='students',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='students_count',
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 16, 18, 11, 34, 889126)),
        ),
    ]
