# Generated by Django 5.1.5 on 2025-06-13 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_exam_students_remove_exam_students_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 17, 15, 37, 54, 87240)),
        ),
    ]
