# Generated by Django 5.1.5 on 2025-06-14 07:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_exam_date'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloze_test',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_cloze_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='fill_gaps',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_fill_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='imageobjectivetest',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_image_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='listening',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_lesson_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='matchpairs',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_match_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='objectivetest',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_objective_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='true_false',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_boolen_file', to='upload.file'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_vocab_file', to='upload.file'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 18, 12, 30, 41, 216425)),
        ),
    ]
