# Generated by Django 5.1.5 on 2025-06-14 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_cloze_test_file_fill_gaps_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairs',
            name='key',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 18, 13, 23, 22, 465288)),
        ),
    ]
