# Generated by Django 5.1.5 on 2025-06-14 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_examregistration_certificate_expire_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloze_test',
            old_name='answer',
            new_name='sentence',
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 18, 17, 30, 29, 916743)),
        ),
    ]
