# Generated by Django 5.1.5 on 2025-06-14 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_rename_answer_cloze_test_sentence_alter_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 18, 18, 26, 50, 942903)),
        ),
    ]
