# Generated by Django 5.1.5 on 2025-06-14 13:51

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
        ('quiz', '0017_alter_exam_date'),
        ('subject', '0003_subject_is_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='lang_group',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AddField(
            model_name='exam',
            name='lang_foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='lang_national',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 18, 18, 50, 58, 675794)),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='options',
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('options', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1, null=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_subject_quiz', to='subject.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='options',
            field=models.ManyToManyField(related_name='exam_subject_options', to='quiz.examsubject'),
        ),
    ]
