# Generated by Django 5.1.5 on 2025-06-16 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_remove_exam_lang_group_remove_exam_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 20, 14, 22, 46, 898443)),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='options',
            field=models.CharField(blank=True, default=1, max_length=2, null=True),
        ),
    ]
