# Generated by Django 5.1.5 on 2025-06-16 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_quiz_type_alter_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 20, 18, 30, 10, 316034)),
        ),
    ]
