# Generated by Django 5.1.5 on 2025-03-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
