# Generated by Django 5.1.4 on 2025-01-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('DIRECTOR', 'Director'), ('CALL_CENTER', 'Call Center'), ('ACCOUNTING', 'ACCOUNTING'), ('TEACHER', 'Teacher')], default='ADMINISTRATOR', max_length=20),
        ),
    ]
