# Generated by Django 5.1.5 on 2025-05-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='second_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
