# Generated by Django 5.1.5 on 2025-03-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monitoring',
            field=models.FloatField(default=0),
        ),
    ]
