# Generated by Django 5.1.4 on 2025-01-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_delete',
        ),
    ]
