# Generated by Django 5.1.5 on 2025-06-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_calculate_penalties'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='calculate_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
