# Generated by Django 5.1.5 on 2025-05-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_second_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='second_user',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
