# Generated by Django 5.1.5 on 2025-03-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_monitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CALL_OPERATOR', 'Call Center'), ('ADMINISTRATOR', 'Sales Menejeri'), ('SERVICE_MANAGER', 'Service Manager'), ('ACCOUNTING', 'Accounting'), ('ATTENDANCE_MANAGER', 'Attendance Manager'), ('FILIAL_Manager', 'Filial Manager'), ('HEAD_TEACHER', 'Head Teacher'), ('MONITORING_MANAGER', 'Monitoring Manager'), ('TESTOLOG', 'Testolog'), ('TEACHER', 'Teacher'), ('ASSISTANT', 'Assistant teacher'), ('MULTIPLE_FILIAL_MANAGER', 'Multiple Filial Manager'), ('DIRECTOR', 'Director'), ('Student', 'Student'), ('Parents', 'Parents')], default='DIRECTOR', max_length=30),
        ),
    ]
