# Generated by Django 5.1.5 on 2025-06-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_second_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='calculate_penalties',
            field=models.BooleanField(default=False),
        ),
    ]
