# Generated by Django 5.1.4 on 2025-01-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_can_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('DIRECTOR', 'Director'), ('CALL_CENTER', 'Call Center'), ('ACCOUNTING', 'Accounting'), ('TEACHER', 'Teacher')], default='ADMINISTRATOR', max_length=20),
        ),
    ]
