# Generated by Django 5.1.5 on 2025-03-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_role'),
        ('filial', '0001_initial'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='account_files', to='upload.file'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='filial',
            field=models.ManyToManyField(blank=True, related_name='users_filials', to='filial.filial'),
        ),
    ]
