# Generated by Django 5.1.4 on 2025-01-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('MODERATOR', 'Moderator'), ('DIRECTOR', 'Director'), ('CALL_CENTER', 'Call Center'), ('ACCOUNTING', 'Accounting'), ('TEACHER', 'Teacher')], default='ADMINISTRATOR', max_length=20),
        ),
    ]
