# Generated by Django 5.1.5 on 2025-05-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_attendance',
            old_name='user',
            new_name='employee',
        ),
    ]
