# Generated by Django 5.1.5 on 2025-05-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_rename_user_employee_attendance_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_attendance',
            old_name='employee',
            new_name='user',
        ),
    ]
