# Generated by Django 5.1.5 on 2025-05-22 06:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_remove_employee_attendance_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_attendance',
            name='action',
        ),
        migrations.RemoveField(
            model_name='employee_attendance',
            name='type',
        ),
        migrations.RemoveField(
            model_name='employee_attendance',
            name='user',
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendance', to=settings.AUTH_USER_MODEL, to_field='second_user'),
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='not_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('On_time', 'On_time'), ('Late', 'Late'), ('Absent', 'Absent'), ('Gone', 'Gone')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 22)),
        ),
    ]
