# Generated by Django 5.1.5 on 2025-06-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0003_remove_employee_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff_attendance',
            name='status',
            field=models.CharField(choices=[('Late', 'Late'), ('On_time', 'On_time'), ('Absent', 'Absent')], default=1),
            preserve_default=False,
        ),
    ]
