# Generated by Django 5.1.5 on 2025-05-23 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0003_remove_employee_attendance_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 23)),
        ),
    ]
