# Generated by Django 5.1.5 on 2025-05-20 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0003_rename_employee_employee_attendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_attendance',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='employee_attendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='employee_attendance',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='employee_attendance',
            name='not_marked',
        ),
        migrations.RemoveField(
            model_name='employee_attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='action',
            field=models.CharField(blank=True, choices=[('In_office', 'In_office'), ('Gone', 'Gone'), ('Apsent', 'Apsent')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='type',
            field=models.CharField(blank=True, choices=[('On_time', 'On_time'), ('Late', 'Late')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='employee_attendance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
