# Generated by Django 5.1.5 on 2025-06-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0004_stuff_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff_attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('Late', 'Late'), ('On_time', 'On_time'), ('Absent', 'Absent')], max_length=10, null=True),
        ),
    ]
