# Generated by Django 5.1.5 on 2025-06-24 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0004_alter_employee_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 24)),
        ),
        migrations.AlterField(
            model_name='stuff_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 24)),
        ),
    ]
