# Generated by Django 5.1.5 on 2025-05-20 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0004_remove_employee_attendance_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_attendance',
            old_name='user',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='employee_attendance',
            name='action',
        ),
        migrations.RemoveField(
            model_name='employee_attendance',
            name='type',
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='not_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('On_time', 'On_time'), ('Late', 'Late')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 20)),
        ),
    ]
