# Generated by Django 5.1.5 on 2025-06-12 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0005_alter_stuff_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff_attendance',
            name='actions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertimeline',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertimeline',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertimeline',
            name='penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employee_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 12)),
        ),
        migrations.AlterField(
            model_name='employee_attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('In_office', 'In_office'), ('Gone', 'Gone'), ('Absent', 'Absent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stuff_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 12)),
        ),
    ]
