# Generated by Django 5.1.5 on 2025-05-20 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0005_rename_user_employee_attendance_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_attendance',
            name='second_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TimeTracker User Id'),
        ),
        migrations.AlterField(
            model_name='employee_attendance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendance', to=settings.AUTH_USER_MODEL),
        ),
    ]
