# Generated by Django 5.1.5 on 2025-05-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0007_alter_employee_attendance_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_attendance',
            name='second_user',
        ),
    ]
