# Generated by Django 5.1.5 on 2025-06-03 06:30

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
        ('timetracker', '0008_alter_employee_attendance_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_attendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='employee_attendance',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='employee_attendance',
            name='not_marked',
        ),
        migrations.AlterField(
            model_name='employee_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 3)),
        ),
        migrations.AlterField(
            model_name='employee_attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('In_office', 'In_office'), ('Gone', 'Gone'), ('Absent', 'Absent')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Stuff_Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('not_marked', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date(2025, 6, 3))),
                ('amount', models.FloatField(default=0)),
                ('action', models.CharField(blank=True, choices=[('In_side', 'In_side'), ('Outside', 'Outside')], max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Late', 'Late'), ('On_time', 'On_time'), ('Absent', 'Absent')], max_length=10, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_part_attendance', to=settings.AUTH_USER_MODEL, to_field='second_user')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee_attendance',
            name='attendance',
            field=models.ManyToManyField(related_name='employee_full_attendance', to='timetracker.stuff_attendance'),
        ),
    ]
