# Generated by Django 5.1.5 on 2025-05-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0008_remove_employee_attendance_second_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_attendance',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
    ]
