# Generated by Django 5.1.5 on 2025-05-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0009_employee_attendance_is_merged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_attendance',
            name='is_merged',
        ),
    ]
