# Generated by Django 5.1.5 on 2025-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0011_alter_employee_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('On_time', 'On_time'), ('Late', 'Late'), ('Absent', 'Absent'), ('Gone', 'Gone')], max_length=10, null=True),
        ),
    ]
