# Generated by Django 5.1.5 on 2025-05-31 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0018_alter_employee_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 31)),
        ),
    ]
