# Generated by Django 5.1.5 on 2025-06-03 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0020_remove_employee_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimeline',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertimeline',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertimeline',
            name='penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employee_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 3)),
        ),
        migrations.AlterField(
            model_name='stuff_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 3)),
        ),
    ]
