# Generated by Django 5.1.5 on 2025-06-04 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0021_usertimeline_bonus_usertimeline_is_weekend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff_attendance',
            name='actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 4)),
        ),
        migrations.AlterField(
            model_name='stuff_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 4)),
        ),
    ]
