# Generated by Django 5.1.5 on 2025-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0022_stuff_attendance_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff_attendance',
            name='actions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
