# Generated by Django 5.1.5 on 2025-06-05 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0023_alter_stuff_attendance_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 5)),
        ),
        migrations.AlterField(
            model_name='stuff_attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 5)),
        ),
    ]
