# Generated by Django 5.1.5 on 2025-03-15 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('new_lid', '0002_alter_lid_date_of_birth'),
        ('student', '0002_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestudent',
            name='lid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_lid.lid'),
        ),
        migrations.AlterField(
            model_name='salestudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_student_sale', to='student.student'),
        ),
    ]
