# Generated by Django 5.1.5 on 2025-05-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Click', 'Click'), ('Payme', 'Payme'), ('Cash', 'Naqt pul'), ('Card', 'Card'), ('Money_send', "Pul o'tkazish")], max_length=100, null=True),
        ),
    ]
