# Generated by Django 5.1.5 on 2025-06-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casher',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casher',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
