# Generated by Django 5.1.5 on 2025-03-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_salestudent_lid_alter_salestudent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestudent',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
