# Generated by Django 5.1.5 on 2025-06-12 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_finance_payment_method'),
        ('groups', '0003_alter_group_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestudent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_group_sale_student', to='groups.group'),
        ),
    ]
