# Generated by Django 5.1.5 on 2025-03-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_salestudent_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED')], default='ACTIVE', max_length=20, null=True),
        ),
    ]
