# Generated by Django 5.1.5 on 2025-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_sale_type_voucher_voucherstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
