# Generated by Django 5.1.5 on 2025-04-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_voucher_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='is_given',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
