# Generated by Django 5.1.5 on 2025-04-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('subject', '0002_theme_repeated_theme_alter_theme_course_work_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='courses', to='subject.theme'),
        ),
    ]
