# Generated by Django 5.1.4 on 2025-01-13 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_options'),
        ('new_lid', '0017_remove_lid_comment_alter_lid_date_of_birth'),
        ('student', '0017_remove_student_comment_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='lid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_lid.lid'),
        ),
        migrations.AddField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
