# Generated by Django 5.1.5 on 2025-05-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastering', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastering',
            options={'ordering': ('created_at',)},
        ),
    ]
