# Generated by Django 5.1.5 on 2025-05-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastering', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteringteachers',
            name='bonus',
            field=models.BooleanField(default=False),
        ),
    ]
