# Generated by Django 5.1.5 on 2025-05-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastering', '0003_alter_mastering_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteringteachers',
            name='bonus',
            field=models.BooleanField(default=False),
        ),
    ]
