# Generated by Django 5.1.5 on 2025-06-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastering', '0004_masteringteachers_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastering',
            name='choice',
            field=models.CharField(blank=True, choices=[('Homework', 'Homework'), ('Test', 'Test'), ('Speaking', 'Speaking')], default='Homework', null=True),
        ),
    ]
