# Generated by Django 5.1.5 on 2025-03-10 17:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('repeated', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('IS_PRESENT', 'Is Present'), ('REASONED', 'Sababli'), ('UNREASONED', 'Sababsiz'), ('HOLIDAY', 'Dam olish kuni')], default='UNREASONED', help_text='Attendance reason (Sababli/Sababsiz)', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
