# Generated by Django 5.1.5 on 2025-03-10 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('groups', '0001_initial'),
        ('new_lid', '0001_initial'),
        ('student', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_group', to='groups.group'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_lid', to='new_lid.lid'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_student', to='student.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='theme',
            field=models.ManyToManyField(blank=True, null=True, related_name='attendance_theme', to='subject.theme'),
        ),
    ]
