# Generated by Django 5.1.5 on 2025-05-21 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        ('filial', '0001_initial'),
        ('groups', '0001_initial'),
        ('new_lid', '0001_initial'),
        ('student', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_lid', to='new_lid.lid'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_student', to='student.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='attendance_theme', to='subject.theme'),
        ),
        migrations.AddField(
            model_name='secondaryattendance',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial'),
        ),
        migrations.AddField(
            model_name='secondaryattendance',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_group_attendance_secondary_group', to='groups.secondarygroup'),
        ),
        migrations.AddField(
            model_name='secondaryattendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_attendance_student', to='student.student'),
        ),
        migrations.AddField(
            model_name='secondaryattendance',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_group_attendance_theme', to='subject.theme'),
        ),
    ]
