# Generated by Django 5.1.5 on 2025-04-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='amount',
            field=models.CharField(blank=True, help_text='Attendance counted amount ...', max_length=20, null=True),
        ),
    ]
