# Generated by Django 5.1.4 on 2025-01-09 13:38

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('filial', '0001_initial'),
        ('marketing_channel', '0001_initial'),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2025, 1, 9, 13, 38, 43, 780268))),
                ('education_lang', models.CharField(choices=[('ENG', 'ENG'), ('RU', 'RU'), ('UZB', 'UZB')], default='UZB', max_length=100)),
                ('student_type', models.CharField(default='student', max_length=100)),
                ('edu_class', models.CharField(help_text='Education level at school if student studies at school', max_length=100)),
                ('subject', models.CharField(help_text='Subject that student won at competition', max_length=100, null=True)),
                ('ball', models.IntegerField(blank=True, default=0, help_text='Earned ball at competition', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Is this student archived or not')),
                ('comment', models.ForeignKey(help_text='Comment', on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
                ('filial', models.ForeignKey(blank=True, help_text='Filial for this student', null=True, on_delete=django.db.models.deletion.CASCADE, to='filial.filial')),
                ('marketing_channel', models.ForeignKey(help_text='Marketing channel for this student', on_delete=django.db.models.deletion.CASCADE, to='marketing_channel.marketingchannel')),
                ('student_stages', models.ForeignKey(help_text='NewStudentStages for this student', on_delete=django.db.models.deletion.CASCADE, to='stages.newstudentstages')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
