# Generated by Django 5.1.5 on 2025-05-22 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 5, 22, 6, 13, 50, 388237, tzinfo=datetime.timezone.utc)),
        ),
    ]
