# Generated by Django 5.1.5 on 2025-05-20 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 5, 20, 12, 22, 20, 490836, tzinfo=datetime.timezone.utc)),
        ),
    ]
