# Generated by Django 5.1.5 on 2025-03-17 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 12, 40, 7, 480614, tzinfo=datetime.timezone.utc)),
        ),
    ]
