# Generated by Django 5.1.5 on 2025-03-17 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='new_student_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 12, 46, 48, 750986, tzinfo=datetime.timezone.utc)),
        ),
    ]
