# Generated by Django 5.1.5 on 2025-06-12 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 12, 8, 46, 47, 149234, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='frozen_days',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 12, 13, 46, 47, 149504), null=True),
        ),
    ]
