# Generated by Django 5.1.4 on 2025-01-11 13:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_studentstages'),
        ('student', '0008_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_stages',
            new_name='new_student_stages',
        ),
        migrations.AddField(
            model_name='student',
            name='active_student_stages',
            field=models.ForeignKey(default=1, help_text='StudentStages for this student', on_delete=django.db.models.deletion.CASCADE, to='stages.studentstages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_stage_type',
            field=models.CharField(choices=[('NEW_STUDENT', 'NEW_STUDENT'), ('ACTIVE_STUDENT', 'ACTIVE_STUDENT')], default='NEW_STUDENT', help_text='Student stage type', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 11, 13, 40, 43, 861815)),
        ),
    ]
