# Generated by Django 5.1.5 on 2025-03-17 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_active_date_student_new_student_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 16, 40, 16, 68201, tzinfo=datetime.timezone.utc)),
        ),
    ]
