# Generated by Django 5.1.4 on 2025-01-11 13:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_channel', '0002_alter_marketingchannel_options'),
        ('stages', '0003_studentstages'),
        ('student', '0009_rename_student_stages_student_new_student_stages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active_student_stages',
            field=models.ForeignKey(blank=True, help_text='StudentStages for this student', null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.studentstages'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 11, 13, 44, 33, 780061)),
        ),
        migrations.AlterField(
            model_name='student',
            name='marketing_channel',
            field=models.ForeignKey(blank=True, help_text='Marketing channel for this student', null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing_channel.marketingchannel'),
        ),
        migrations.AlterField(
            model_name='student',
            name='new_student_stages',
            field=models.ForeignKey(blank=True, help_text='NewStudentStages for this student', null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.newstudentstages'),
        ),
    ]
