# Generated by Django 5.1.5 on 2025-03-23 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 23, 6, 51, 46, 959179, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='new_student_stages',
            field=models.CharField(blank=True, choices=[('BIRINCHI_DARS', 'BIRNCHI_DARS'), ('BIRINCHI_DARSGA_KELMAGAN', 'BIRINCHI_DARSGA_KELMAGAN'), ("GURUH_O'ZGARTIRGAN", "GURUH_O'ZGARTIRGAN"), ('QARIZDOR', 'QARIZDOR')], default='BIRNCHI_DARS', help_text='Student stage type', max_length=100, null=True),
        ),
    ]
