# Generated by Django 5.1.5 on 2025-03-23 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 23, 6, 51, 50, 401510, tzinfo=datetime.timezone.utc)),
        ),
    ]
