# Generated by Django 5.1.4 on 2025-01-11 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_moderator_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 1, 11, 14, 2, 5, 883800)),
        ),
    ]
