# Generated by Django 5.1.5 on 2025-05-21 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 5, 21, 11, 0, 36, 400570, tzinfo=datetime.timezone.utc)),
        ),
    ]
