# Generated by Django 5.1.5 on 2025-03-23 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 23, 11, 6, 53, 982283, tzinfo=datetime.timezone.utc)),
        ),
    ]
