# Generated by Django 5.1.5 on 2025-03-24 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 24, 10, 45, 37, 227749, tzinfo=datetime.timezone.utc)),
        ),
    ]
