# Generated by Django 5.1.5 on 2025-05-28 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='frozen_days',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 5, 28, 10, 41, 38, 695371), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 5, 28, 5, 41, 38, 695060, tzinfo=datetime.timezone.utc)),
        ),
    ]
