# Generated by Django 5.1.5 on 2025-03-28 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_student_user_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 28, 5, 13, 12, 839684, tzinfo=datetime.timezone.utc)),
        ),
    ]
