# Generated by Django 5.1.5 on 2025-03-28 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_alter_student_date_of_birth_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 28, 13, 10, 21, 716467, tzinfo=datetime.timezone.utc)),
        ),
    ]
