# Generated by Django 5.1.5 on 2025-03-29 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 29, 11, 53, 38, 107733, tzinfo=datetime.timezone.utc)),
        ),
    ]
