# Generated by Django 5.1.5 on 2025-04-01 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 4, 1, 14, 3, 19, 900876, tzinfo=datetime.timezone.utc)),
        ),
    ]
