# Generated by Django 5.1.5 on 2025-04-02 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 10, 52, 46, 17283, tzinfo=datetime.timezone.utc)),
        ),
    ]
