# Generated by Django 5.1.5 on 2025-04-03 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_alter_student_date_of_birth_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 4, 3, 11, 32, 35, 454871, tzinfo=datetime.timezone.utc)),
        ),
    ]
