# Generated by Django 5.1.5 on 2025-04-08 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_alter_student_options_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 4, 8, 12, 5, 33, 806222, tzinfo=datetime.timezone.utc)),
        ),
    ]
