# Generated by Django 5.1.5 on 2025-04-09 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 4, 9, 11, 25, 25, 448972, tzinfo=datetime.timezone.utc)),
        ),
    ]
