# Generated by Django 5.1.5 on 2025-06-05 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0047_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 5, 9, 26, 43, 510241, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='frozen_days',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 5, 14, 26, 43, 510536), null=True),
        ),
    ]
