# Generated by Django 5.1.5 on 2025-06-14 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0063_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 6, 14, 8, 23, 22, 351386, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='frozen_days',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 14, 13, 23, 22, 351728), null=True),
        ),
    ]
