# Generated by Django 5.1.5 on 2025-04-26 07:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
        ('subject', '0001_initial'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('documents', models.ManyToManyField(blank=True, related_name='homework_documents', to='upload.file')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('photo', models.ManyToManyField(blank=True, related_name='homework_photo', to='upload.file')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes_homework', to='subject.theme')),
                ('video', models.ManyToManyField(blank=True, related_name='homeworks_video', to='upload.file')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
            },
        ),
    ]
