# Generated by Django 5.1.5 on 2025-05-20 12:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
        ('subject', '0001_initial'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('choice', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20, null=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='homework_documents', to='upload.file')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('photo', models.ManyToManyField(blank=True, related_name='homework_photo', to='upload.file')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes_homework', to='subject.theme')),
                ('video', models.ManyToManyField(blank=True, related_name='homeworks_video', to='upload.file')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
            },
        ),
        migrations.CreateModel(
            name='Homework_history',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Retake', 'Retake')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('mark', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks_history', to='homeworks.homework')),
            ],
            options={
                'verbose_name': 'Homeworks History',
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
