# Generated by Django 5.1.5 on 2025-05-13 13:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
        ('homeworks', '0001_initial'),
        ('student', '0006_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='choice',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Homework_history',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Retake', 'Retake')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('mark', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks_history', to='homeworks.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homeworks_history', to='student.student')),
            ],
            options={
                'verbose_name': 'Homeworks History',
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
