# Generated by Django 5.1.5 on 2025-03-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='homework_documents', to='upload.file'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='homework_photo', to='upload.file'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='homeworks_video', to='upload.file'),
        ),
    ]
