# Generated by Django 5.1.5 on 2025-05-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework_history',
            options={'ordering': ['created_at'], 'verbose_name': 'Homeworks History', 'verbose_name_plural': 'Histories'},
        ),
    ]
