# Generated by Django 5.1.5 on 2025-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='test_checked',
            field=models.BooleanField(default=False),
        ),
    ]
