# Generated by Django 5.1.4 on 2025-01-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0002_alter_finans_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finans',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='finans',
            name='lid',
        ),
        migrations.RemoveField(
            model_name='finans',
            name='student',
        ),
        migrations.AddField(
            model_name='finans',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
