# Generated by Django 5.1.5 on 2025-03-24 10:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
        ('filial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='ResultName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('point_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Ball', 'Ball'), ('Degree', 'Degree')], max_length=10)),
                ('type', models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two')], max_length=10, null=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoringAsos4',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.asos')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.resultname')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultSubjects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('result_type', models.CharField(blank=True, choices=[('Mine', 'Mine'), ('Student', 'Student')], max_length=256, null=True)),
                ('point', models.CharField(blank=True, max_length=10, null=True)),
                ('max_ball', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_point', models.CharField(blank=True, max_length=10, null=True)),
                ('to_point', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('asos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.asos')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.resultname')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCatchingMonitoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('from_student', models.CharField(max_length=256)),
                ('to_student', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(choices=[('Bonus', 'Bonus'), ('Compensation', 'Compensation')], max_length=256)),
                ('ball', models.FloatField(blank=True, default=0, null=True)),
                ('asos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.asos')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCountMonitoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('max_ball', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('from_point', models.CharField(blank=True, max_length=256, null=True)),
                ('to_point', models.CharField(blank=True, max_length=256, null=True)),
                ('asos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.asos')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
