# Generated by Django 5.1.5 on 2025-05-21 11:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
        ('filial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asos1_2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asos', models.CharField(blank=True, choices=[('asos1', 'asos1'), ('asos2', 'asos2')], max_length=256, null=True)),
                ('ball', models.FloatField(blank=True, default=0, null=True)),
                ('type', models.CharField(blank=True, choices=[('Bonus', 'Bonus'), ('Compensation', 'Compensation')], max_length=256, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoringAsos1_2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asos', models.CharField(blank=True, choices=[('asos1', 'asos1'), ('asos2', 'asos2')], max_length=256, null=True)),
                ('ball', models.FloatField(blank=True, default=0, null=True)),
                ('type', models.CharField(blank=True, choices=[('Bonus', 'Bonus'), ('Compensation', 'Compensation')], max_length=256, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitoring Asos 1 va 2',
                'verbose_name_plural': 'Monitoring',
            },
        ),
    ]
