# Generated by Django 5.1.5 on 2025-04-11 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compensation', '0001_initial'),
        ('filial', '0001_initial'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringasos4',
            name='result_frk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='results.results'),
        ),
        migrations.AddField(
            model_name='monitoringasos4',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial'),
        ),
        migrations.AddField(
            model_name='page',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='point',
            name='asos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.asos'),
        ),
        migrations.AddField(
            model_name='point',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_monitoring', to='compensation.point'),
        ),
        migrations.AddField(
            model_name='resultname',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial'),
        ),
        migrations.AddField(
            model_name='monitoringasos4',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compensation.resultname'),
        ),
        migrations.AddField(
            model_name='resultsubjects',
            name='asos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.asos'),
        ),
        migrations.AddField(
            model_name='resultsubjects',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial'),
        ),
        migrations.AddField(
            model_name='resultsubjects',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compensation.resultname'),
        ),
        migrations.AddField(
            model_name='monitoringasos4',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compensation.resultsubjects'),
        ),
        migrations.AddField(
            model_name='studentcatchingmonitoring',
            name='asos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.asos'),
        ),
        migrations.AddField(
            model_name='studentcatchingmonitoring',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial'),
        ),
        migrations.AddField(
            model_name='studentcatchingmonitoring',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StudentCatchingMonitoring_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcountmonitoring',
            name='asos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.asos'),
        ),
        migrations.AddField(
            model_name='studentcountmonitoring',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial'),
        ),
        migrations.AddField(
            model_name='studentcountmonitoring',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_count_monitoring_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
