# Generated by Django 5.1.5 on 2025-03-24 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0002_point_amount_resultname_monitoringasos4_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringasos4',
            name='ball',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='monitoringasos4',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compensation.resultsubjects'),
        ),
        migrations.AlterField(
            model_name='monitoringasos4',
            name='asos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compensation.asos'),
        ),
        migrations.AlterField(
            model_name='monitoringasos4',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compensation.resultname'),
        ),
        migrations.AlterField(
            model_name='monitoringasos4',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
