# Generated by Django 5.1.5 on 2025-05-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0003_asos1_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringasos1_2',
            options={'ordering': ['-created_at']},
        ),
    ]
