# Generated by Django 5.1.5 on 2025-05-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0003_alter_monitoringasos1_2_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultname',
            name='who',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Teacher', max_length=10, null=True),
        ),
    ]
