# Generated by Django 5.1.5 on 2025-03-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0004_monitoring_creator_studentcountmonitoring_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='counter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
