# Generated by Django 5.1.5 on 2025-03-25 14:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0005_monitoring_counter'),
        ('filial', '0001_initial'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringasos4',
            options={'verbose_name': 'Monitoring 5 Natijalari', 'verbose_name_plural': 'Monitoring 5'},
        ),
        migrations.AddField(
            model_name='comments',
            name='monitoring',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compensation.monitoring'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoringasos4',
            name='result_frk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='results.results'),
        ),
        migrations.CreateModel(
            name='Monitoring5',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ball', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_count', models.CharField(blank=True, max_length=10, null=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
