# Generated by Django 5.1.5 on 2025-05-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0005_resultname_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsubjects',
            name='degree',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='resultsubjects',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('Grant', 'Grant'), ('Contract', 'Contract')], max_length=10, null=True),
        ),
    ]
