# Generated by Django 5.1.5 on 2025-05-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0005_resultsubjects_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsubjects',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('Grant', 'Grant'), ('Contract', 'Contract')], max_length=10, null=True),
        ),
    ]
