# Generated by Django 5.1.5 on 2025-03-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0006_alter_monitoringasos4_options_comments_monitoring_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringasos4',
            options={'verbose_name': 'Monitoring 5', 'verbose_name_plural': 'Monitoring 5'},
        ),
    ]
