# Generated by Django 5.1.5 on 2025-05-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0006_resultsubjects_degree_resultsubjects_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringasos4',
            name='type',
            field=models.CharField(blank=True, choices=[('Olimpiada', 'Olimpiada'), ('Certificate', 'Certificate'), ('University', 'University')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resultname',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultsubjects',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
