# Generated by Django 5.1.5 on 2025-05-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0006_resultsubjects_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultname',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultsubjects',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
