# Generated by Django 5.1.5 on 2025-05-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0007_resultname_is_archived_resultsubjects_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringasos4',
            name='type',
            field=models.CharField(blank=True, choices=[('Olimpiada', 'Olimpiada'), ('Certificate', 'Certificate'), ('University', 'University')], max_length=15, null=True),
        ),
    ]
