# Generated by Django 5.1.5 on 2025-03-26 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0007_alter_monitoringasos4_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoring',
            options={'verbose_name': 'Monitoring', 'verbose_name_plural': 'Monitoring 3, 12, 13, 14'},
        ),
        migrations.AlterModelOptions(
            name='monitoring5',
            options={'verbose_name': 'Monitoring 5', 'verbose_name_plural': 'Monitoring 5'},
        ),
        migrations.AlterModelOptions(
            name='monitoringasos4',
            options={'verbose_name': 'Monitoring 4', 'verbose_name_plural': 'Monitoring 4'},
        ),
        migrations.AlterModelOptions(
            name='resultname',
            options={'verbose_name': 'Natijalar', 'verbose_name_plural': 'Natijalar monitoringi'},
        ),
        migrations.AlterModelOptions(
            name='resultsubjects',
            options={'verbose_name': 'Monitoring', 'verbose_name_plural': 'Natija turi'},
        ),
        migrations.AlterModelOptions(
            name='studentcatchingmonitoring',
            options={'verbose_name': 'Monitoring', 'verbose_name_plural': "O'quvchini olib qolish monitoringi"},
        ),
        migrations.AlterModelOptions(
            name='studentcountmonitoring',
            options={'verbose_name': 'Monitoring', 'verbose_name_plural': "O'quvchini soni monitoringi"},
        ),
        migrations.AddField(
            model_name='monitoringasos4',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MonitoringAsos4_creator_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
