# Generated by Django 5.1.5 on 2025-03-26 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0008_alter_monitoring_options_alter_monitoring5_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsubjects',
            name='level',
            field=models.CharField(blank=True, choices=[('Region', 'Region'), ('Regional', 'Regional')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='resultsubjects',
            name='university_type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('National', 'National')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='studentcatchingmonitoring',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StudentCatchingMonitoring_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcountmonitoring',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_count_monitoring_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='ball',
            field=models.CharField(blank=True, help_text="This ball can not be higher than asos's max_ball !!!", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monitoring5',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Monitoring5_creator_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monitoringasos4',
            name='ball',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='resultsubjects',
            name='amount',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='resultsubjects',
            name='max_ball',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
