# Generated by Django 5.1.5 on 2025-03-28 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0010_alter_resultsubjects_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asos',
            options={'ordering': ['created_at']},
        ),
    ]
