# Generated by Django 5.1.5 on 2025-04-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0012_alter_bonus_name_alter_compensation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='name',
            field=models.CharField(blank=True, choices=[('Markazga kelgan o‘quvchi uchun bonus', 'Markazga kelgan o‘quvchi uchun bonus'), ('Yaratilgan buyurtma uchun bonus', 'Yaratilgan buyurtma uchun bonus'), ('Sinov darsiga kelgani uchun bonus', 'Sinov darsiga kelgani uchun bonus'), ("Hizmat ko’rsatgan har bir Aktiv o'quvchi uchun bonus", "Hizmat ko’rsatgan har bir Aktiv o'quvchi uchun bonus"), ("Aktiv o'quvchiga aylangan yangi o’quvchi uchun bonus", "Aktiv o'quvchiga aylangan yangi o’quvchi uchun bonus"), ("Har bir qarzdor bo’lmagan va Aktiv o'quvchi uchun bonus", "Har bir qarzdor bo’lmagan va Aktiv o'quvchi uchun bonus"), ("Jami yangi va aktiv o'quvchi o'quvchilarning 93% dan 94.9% gacha bo'lgan qismi uchun bonus", "Jami yangi va aktiv o'quvchi o'quvchilarning 93% dan 94.9% gacha bo'lgan qismi uchun bonus"), ("Jami yangi va aktiv o'quvchi o'quvchilarning 95% dan 97.9% gacha bo'lgan qismi uchun bonus", "Jami yangi va aktiv o'quvchi o'quvchilarning 95% dan 97.9% gacha bo'lgan qismi uchun bonus"), ("Jami yangi va aktiv o'quvchi o'quvchilarning 98% dan 99.9% gacha bo'lgan qismi uchun bonus", "Jami yangi va aktiv o'quvchi o'quvchilarning 98% dan 99.9% gacha bo'lgan qismi uchun bonus"), ("Jami yangi va aktiv o'quvchi o'quvchilarning 100% gacha bo'lgan qismi uchun bonus", "Jami yangi va aktiv o'quvchi o'quvchilarning 100% gacha bo'lgan qismi uchun bonus"), ("Aktiv o'quvchi soniga bonus", "Aktiv o'quvchi soniga bonus"), ('Bir oyda 10 marta kelgan har bir oquvchi uchun bonus', 'Bir oyda 10 marta kelgan har bir oquvchi uchun bonus'), ('O’quvchi to’lagan summadan foiz beriladi', 'O’quvchi to’lagan summadan foiz beriladi')], max_length=256, null=True),
        ),
    ]
