# Generated by Django 5.1.5 on 2025-04-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='points',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
